parameters:
- name: k8s_cluster
  type: string
  default: ''

- name: release
  type: string
  default: ''

- name: values
  type: string
  default: ''

- name: env
  type: string
  default: ''

- name: chart_ver
  type: string
  default: ''
  

steps:
- task: HelmDeploy@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'DXO_Service_Connection'
    azureResourceGroup: 'DXO_Integration_RG'
    kubernetesCluster: '${{ parameters.k8s_cluster }}_${{ parameters.env }}'
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: '$(Build.SourcesDirectory)/helm/dotnet'
    valueFile: '$(Build.SourcesDirectory)/helm/dotnet/${{ parameters.values }}'
    releaseName: '${{ parameters.release }}-${{ parameters.env }}'
    chartVersion: '${{ parameters.chart_ver }}'